baseurl = "http://vjeantet.fr/"
languageCode = "fr-FR"
title = "Valère JEANTET"
paginate = 5
DisqusShortname = "vjeantet"
Copyright = "All rights reserved - 2015"

[params]
  description = "Whatever the mind of man can conceive and believe, it can achieve."
  cover = "images/cover_polenord.jpg"
  author = "Valère JEANTET"
  authorlocation = "Paris, France"
  authorwebsite = "http://vjeantet.fr"
  bio= "IT software and Security Engineer, Open source enthusiast."
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  githubName = "vjeantet"
  twitterName = "vjeantet"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false


[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "Github repos"
  weight = 100
  url = "http://github.com/vjeantet"

[[menu.main]]
  name = "Twitter timeline"
  weight = 100
  url = "https://twitter.com/vjeantet"

[[menu.main]]
  name = "Flipboard magazines"
  weight = 101
  url = "https://flipboard.com/@vjeantet"

[[menu.main]]
  name = "Keybase (secure msg)"
  weight = 109
  url = "http://Keybase.io/vjeantet"