baseurl = "http://vjeantet.fr/"
copyright = "All rights reserved"
disqusshortname = "vjeantet"
languagecode = "fr-FR"
paginate = 5
pluralizelisttitles = false
theme = "hugo-theme-casper"
title = "Valère JEANTET"
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120
[[menu.main]]
name = "Github repos"
pre = "<h3>Follow me</h3>"
url = "https://github.com/vjeantet"
weight = 100
[[menu.main]]
name = "Twitter timeline"
url = "https://twitter.com/vjeantet"
weight = 101
[[menu.main]]
name = "Flipboard magazines"
url = "https://flipboard.com/@vjeantet"
weight = 102
[[menu.main]]
name = "Keybase (secure msg)"
pre = "<h3>Contact me</h3>"
url = "https://Keybase.io/vjeantet"
weight = 109

[params]
author = "Valère JEANTET"
authorlocation = "Paris, France"
authorwebsite = "http://vjeantet.fr"
authorbio = "IT software and Security Engineer, Open source enthusiast."
cover = "images/cover_polenord.jpg"
description = "Whatever the mind of man can conceive and believe, it can achieve."
githubName = "vjeantet"
googleAnalyticsUserID = "UA-79101-12"
hideHUGOSupport = false
logo = "images/logo.png"
twitterName = "vjeantet"
[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
